version: '3.8'

services:
  blood-test-ai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blood-test-forecasting
    ports:
      - "8505:8505"
    volumes:
      # Mount local files for live development
      - ./blood_test_dashboard_GenAI.py:/app/blood_test_dashboard_GenAI.py
      - ./.env:/app/.env
      - ./requirements.txt:/app/requirements.txt
    environment:
      - STREAMLIT_SERVER_PORT=8505
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      # Load environment variables from .env file
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: unless-stopped
    networks:
      - blood-test-network

networks:
  blood-test-network:
    driver: bridge